methods:
  #GetConfigurationPage
  get:
    query:
      distributorId: ${distributorId}
      channelId: ${channelId}
      productType: ${productType}
    method: post
    url: http://47.96.181.183:10088/h/com.ydl.wo.intf.facade.CpsConfigurationPageFacade/getConfigurationPage